---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
inputs:
- name: brokerbuild
- name: brokerpak
- name: brokerpak-version
run:
  dir: brokerpak
  path: /bin/sh
  args: 
  - -exc
  - |
    export VERSION=$(cat ../brokerpak-version/version)
    mkdir -p brokerpak
    cd brokerpak
    cp -pr ../${BROKERPAKDIR}/* .
    sed "s/^version:.*/version: ${VERSION}/" < ../${BROKERPAKDIR}/manifest.yml > ./manifest.yml
    ../../brokerbuild/cloud-service-broker.linux pak build
outputs:
- name: brokerpak-output
  path: brokerpak/brokerpak
